name: Test
on:
  push:
    branches:
      - main
    paths-ignore:
      - "**/coverage.svg"

permissions:
  contents: write
    
jobs:
  generate-reports:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python 3.13
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: Set up dependencies
      uses: awalsh128/cache-apt-pkgs-action@latest
      with: 
        packages: gcc g++ make cpputest lcov ant
        version: 1.0
  
    - name: Make CppUTest tests
      run: make test

    - name: Create output directories
      run: |
        mkdir -p html
        mkdir -p xml

    - name: Generate test report
      working-directory: xml
      run: |
        ../calc -c -v -ojunit
      continue-on-error: true

    - name: Convert test report to html
      run: |
        pip install jinja2
        python3 gen.py
      continue-on-error: true
    
    - name: Generate coverage report
      run: |
        make coverage
        cp -r coverage html/coverage
      continue-on-error: true

    - name: Copy index.html
      run: cp target.html html/index.html

    # - name: Upload coverage report
    #   uses: JamesIves/github-pages-deploy-action@v4
    #   with:
    #     folder: html/
    
    - name: Upload report as artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: html/

    - name: Deploy artifact to pages
      id: deployment
      uses: actions/deploy-pages@v4

    - name: Run again just for the status
      run: |
        ./calc -c -v