name: Test
on:
  push:
    branches:
      - main
    paths-ignore:
      - "**/coverage.svg"

permissions:
  contents: write
    
jobs:
  generate-reports:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up dependencies
      uses: awalsh128/cache-apt-pkgs-action@latest
      with: 
        packages: gcc g++ make cpputest lcov ant
        version: 1.0
  
    - name: Make CppUTest tests
      run: make test

    - name: Create output directories
      run: |
        mkdir -p html
        mkdir -p xml

    - name: Generate test report
      working-directory: beta
      run: |
        ./calc -c -v -ojunit
      continue-on-error: true

    - name: Convert test report
      working-directory: beta
      run: |
        ant convert
      continue-on-error: true
    
    - name: Generate coverage report
      working-directory: beta
      run: |
        lcov --directory . --capture --output-file coverage.info --ignore-errors mismatch
        genhtml coverage.info --output-directory html/coverage
      continue-on-error: true

    - name: Copy index.html
      run: cp index_example.html html/index.html

    - name: Upload coverage report
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: html/